[package]
name = "memorial_nft"
edition = "2024"         # edition = "legacy" to use legacy (pre-2024) Move
# license = ""           # e.g., "MIT", "GPL", "Apache 2.0"
# authors = ["..."]      # e.g., ["Joe Smith (joesmith@noemail.com)", "John Snow (johnsnow@noemail.com)"]

[dependencies]
MoveStdlib = { local = "/Users/mac/.move/https___github_com_MystenLabs_sui_git_framework__testnet/crates/sui-framework/packages/move-stdlib" }
Sui = { local = "/Users/mac/.move/https___github_com_MystenLabs_sui_git_framework__testnet/crates/sui-framework/packages/sui-framework" }

[addresses]
memorial_nft = "0x0"

# Read more about the package management system options:
# https://docs.sui.io/guides/developer/sui-101/move-package-management
